# Generated by Django 3.1 on 2020-10-07 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.PositiveIntegerField(default=0)),
                ('time_spent', models.DurationField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('passed', models.IntegerField(default=0)),
                ('no_of_questions', models.IntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='dashboard.quiz')),
            ],
        ),
    ]
