# Generated by Django 3.1 on 2020-10-08 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_result_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='failed',
            new_name='no_of_correct_choices_answered',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='passed',
            new_name='no_of_questions_answered',
        ),
    ]
