# Generated by Django 3.1 on 2020-09-02 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='teacher',
            field=models.BooleanField(default=False),
        ),
    ]
