# Generated by Django 3.1 on 2020-10-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='teacher',
            field=models.BooleanField(default=False, help_text='check to register as a teacher. Only teachers can create,delete and update quizzes'),
        ),
    ]
