# Generated by Django 3.1 on 2020-10-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201003_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='teacher',
            field=models.BooleanField(default=False, help_text='check to register as a teacher. Only teachers can create quizzes'),
        ),
    ]
