# Generated by Django 3.1 on 2020-10-03 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='mark',
            field=models.CharField(choices=[('right', 'Right'), ('wrong', 'Wrong')], default='wrong', help_text='is this the right or wrong choice for this question? ', max_length=5),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=300), help_text='HH:MM:SS'),
        ),
    ]
