# Generated by Django 3.1 on 2020-09-20 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200908_0812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='users',
        ),
        migrations.DeleteModel(
            name='Result',
        ),
    ]
